apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
    name: postgres-configmap
data:
  postgresql.conf: |
    listen_addresses = '*'
    dynamic_shared_memory_type = posix
    log_timezone = 'Etc/UTC'
    datestyle = 'iso, mdy'
    timezone = 'Etc/UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
    max_connections = 50
    shared_buffers = 4GB
    effective_cache_size = 12GB
    maintenance_work_mem = 1GB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 27962kB
    min_wal_size = 1GB
    max_wal_size = 4GB
    max_worker_processes = 6
    max_parallel_workers_per_gather = 3
    max_parallel_workers = 6
    max_parallel_maintenance_workers = 3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: postgres-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /cs-storage/postgres-pv
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
     app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: registry-one.codescoring.ru/postgres:13.4
          envFrom:
            - configMapRef:
                name: postgres-configmap
          env:
            - name: POSTGRES_USER
              value: codescoring
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: codescoring
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
            - name: postgres-configmap-volume
              mountPath: /etc/postgresql
          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
      imagePullSecrets:
        - name: cs-registry

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-configmap-volume
          configMap:
            name: postgres-configmap
