apiVersion: batch/v1
kind: Job
metadata:
  name: ipcs-migrations
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: ipcs-migrate
          image: registry-one.codescoring.ru/ipcs-backend:2023.5.0
          command: ['python', 'manage.py', 'migrate']

          envFrom:
          - configMapRef:
              name: ipcs-env
          - secretRef:
              name: ipcs-secrets
          imagePullPolicy: Always
      imagePullSecrets:
        - name: cs-registry

      restartPolicy: OnFailure
  backoffLimit: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ipcs-collectstatic
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: ipcs-collectstatic
          image: registry-one.codescoring.ru/ipcs-backend:2023.5.0
          command: ['python', 'manage.py', 'collectstatic']

          envFrom:
          - configMapRef:
              name: ipcs-env
          - secretRef:
              name: ipcs-secrets
          imagePullPolicy: Always
      imagePullSecrets:
        - name: cs-registry

      restartPolicy: OnFailure
  backoffLimit: 5

