---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-static
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /cs-storage/django-static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analysis-root
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /cs-storage/analysis-root

