apiVersion: v1
kind: Secret
metadata:
  name: ipcs-secrets
type: Opaque
data:
  SECRET_KEY: M3ppMWFjOTZebncrcShsemxxN202YWlmQF5fMG15LXl1b2Jndm5nKChla3l5MD1hOHQK
  DATABASE_URL: cHNxbDovL2NvZGVzY29yaW5nOmNvZGVzY29yaW5nQHBvc3RncmVzOjU0MzIvY29kZXNjb3Jpbmc=
  # USERNAME default: admin@onprem
  DJANGO_SUPERUSER_USERNAME: YWRtaW5Ab25wcmVt
  # PASSWORD default: 9ZsderF1f8WC
  DJANGO_SUPERUSER_PASSWORD: b25wcmVtaXNl
  SENTRY_DSN: ""



