---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: django-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-root-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: analysis-root
