apiVersion: batch/v1
kind: Job
metadata:
  name: ipcs-createsuperuser
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ipcs-createsuperuser
          image: registry-one.codescoring.ru/ipcs-backend
          command: ['python', 'manage.py', 'createsuperuser', '--noinput' ]
          securityContext:
            runAsUser: 1050
            runAsGroup: 1050
          envFrom:
          - configMapRef:
              name: ipcs-env
          - secretRef:
              name: ipcs-secrets
      imagePullSecrets:
        - name: cs-registry

      restartPolicy: Never
  backoffLimit: 1
