apiVersion: v1
kind: ConfigMap
metadata:
  name: ipcs-env
data:
  SITE_SCHEME: "https"
  SITE_HOST: "codescoring.k8s.local"
  NGINX_HOST: "codescoring.k8s.local"
  NGINX_PORT: "8080"
  HOME: "/ipcs-backend"
  AZURE_DEVOPS_CACHE_DIR: "/ipcs-backend"
  BASE_DIR: "/ipcs-backend"
  DJANGO_CACHES_REDIS_URL: "redis://redis:6379/1"
  ANALYSIS_ROOT: "/analysis-root"
  ANALYSIS_IGNORED_PATHS: "**/.git*,**/.git/**,**/fixtures/**,**/tests/**,**/doc/**,**/docs/**,**/samples/**"
  HUEY_REDIS_URL: "redis://redis:6379/0"
  NODE_PATH: "/jscpd/node_modules"
  JOHNNY_BIN: "/agents/johnny-linux-amd64"
  HASHER_BIN: "/agents/hasher-linux-amd64"
  JSCPD_BIN: "/jscpd/node_modules/jscpd/bin/jscpd"
  ALLOWED_HOSTS: "*"
  HUEY_WORKERS: "8"
  INDEX_API_URL: "https://index.codescoring.ru"
  REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:18000"
  SENTRY_ENABLED: "False"
  SENTRY_ENVIRONMENT: ""
  SENTRY_RELEASE: ""
  # pgcat  to postgres creds
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "codescoring"
  POSTGRES_USER: "codescoring"
  # ipcs to pgcat creds
  DATABASE_HOST: pgcat
  DATABASE_PORT: "6432"
  DATABASE_NAME: "codescoring"
  DATABASE_USERNAME: "codescoring"
  PGCAT_POOL_SIZE: "50"
