apiVersion: batch/v1
kind: Job
metadata:
  name: ipcs-migrations
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      volumes:
        - name: analysis-root
          persistentVolumeClaim:
            claimName: analysis-root-pvc
      automountServiceAccountToken: false
      initContainers:
        - name: fix-volume-permissions
          image: registry-one.codescoring.ru/ipcs-backend
          command: ["chown", "-R", "1050:1050", "/analysis-root"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: analysis-root
              mountPath: /analysis-root
      containers:
        - name: ipcs-migrate
          image: registry-one.codescoring.ru/ipcs-backend
          command: ['python', 'manage.py', 'migrate']
          securityContext:
            runAsUser: 1050
            runAsGroup: 1050
          envFrom:
          - configMapRef:
              name: ipcs-env
          - secretRef:
              name: ipcs-secrets
          volumeMounts:
            - name: analysis-root
              mountPath: /analysis-root
          imagePullPolicy: Always
      imagePullSecrets:
        - name: cs-registry
      restartPolicy: OnFailure
  backoffLimit: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ipcs-collectstatic
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      volumes:
        - name: django-static
          persistentVolumeClaim:
            claimName: django-static-pvc
      automountServiceAccountToken: false
      initContainers:
        - name: fix-volume-permissions
          image: registry-one.codescoring.ru/ipcs-backend
          command: ["chown", "-R", "1050:1050", "/ipcs-backend/files"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: django-static
              mountPath: /ipcs-backend/files/static
      containers:
        - name: ipcs-collectstatic
          image: registry-one.codescoring.ru/ipcs-backend
          command: ['python', 'manage.py', 'collectstatic', '--noinput']
          securityContext:
            runAsUser: 1050
            runAsGroup: 1050
          envFrom:
          - configMapRef:
              name: ipcs-env
          - secretRef:
              name: ipcs-secrets
          imagePullPolicy: Always
          volumeMounts:
            - name: django-static
              mountPath: /ipcs-backend/files/static
      imagePullSecrets:
        - name: cs-registry
      restartPolicy: OnFailure
  backoffLimit: 5

