apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ipcs-migration.yaml
  - ./ipcs-createsuperuser.yaml
  - ./ipcs-backend.yaml
  - ./ipcs-frontend.yaml
  - ./ipcs-pgcat.yaml
namespace: codescoring
images:
  - name: registry-one.codescoring.ru/ipcs-huey
    newTag: "2023.38.0-unpriv"
  - name: registry.one.codescoring.ru/ipcs-backend
    newTag: "2023.38.0-unpriv"
  - name: registry-one.codescoring.ru/ipcs-backup
    newTag: "2023.38.0-unpriv"
  - name: registry-one.codescoring.ru/ipcs-frontend
    newTag: "2023.38.0-unpriv"
  - name: registry-one.codescoring.ru/ipcs-pgcat
    newTag: "2023.38.0"
